name: Kopier fil til gh-pages

on:
  workflow_run:
    workflows: ["01 Build and Deploy Site"]
    types:
      - completed

jobs:
  kopier-fil:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages

      - name: Download fil fra internettet
        run: curl -o logotest.svg https://kubdatalab.github.io/R-intro/fig/logotest.svg

      - name: Kopier fil til det bestemte sted
        run: mv logotest.svg assets/images/library-logo.svg

      - name: Hent favicons-mappen fra R-intro (sparse checkout) og kopier til favicons/lc
        run: |
          set -e
          TMPDIR="$(mktemp -d)"
          git clone --depth=1 --filter=blob:none --sparse https://github.com/kubdatalab/R-intro "$TMPDIR"
          cd "$TMPDIR"
          # Prøv fig/favico først; hvis den ikke findes, brug fig/favicon
          if git sparse-checkout set fig/favico 2>/dev/null; then
            SRC_DIR=fig/favico
          else
            git sparse-checkout set fig/favicon
            SRC_DIR=fig/favicon
          fi
          cd -
          mkdir -p favicons/lc
          # Kopiér ALT indhold fra kildemappen til favicons/lc (overskriver eksisterende filer med samme navn)
          cp -r "$TMPDIR/$SRC_DIR/." favicons/lc/

      - name: Commit og push ændringer
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Opdateret fil på gh-pages"
          git push
