name: Kopier fil til gh-pages

on:
  workflow_run:
    workflows: ["01 Build and Deploy Site"]
    types:
      - completed

jobs:
  kopier-fil:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages

      - name: Download fil fra internettet
        run: curl -o logotest.svg https://kubdatalab.github.io/R-intro/fig/logotest.svg

      - name: Kopier fil til det bestemte sted
        run: mv logotest.svg assets/images/library-logo.svg

      - name: Hent favicons fra R-intro og kopier til favicons/lc
        run: |
          set -e
          TMPDIR="$(mktemp -d)"
          git clone --depth=1 https://github.com/kubdatalab/R-intro "$TMPDIR"

          if [ -d "$TMPDIR/fig/favico" ]; then
            SRC_DIR="$TMPDIR/fig/favico"
          elif [ -d "$TMPDIR/fig/favicon" ]; then
            SRC_DIR="$TMPDIR/fig/favicon"
          else
            echo "Fandt hverken fig/favico eller fig/favicon i R-intro-repoet" >&2
            exit 1
          fi

          mkdir -p favicons/lc
          # Kopiér alt indhold (bevarer timestamps/permissions hvor muligt)
          cp -a "$SRC_DIR/." favicons/lc/

      - name: Commit og push ændringer
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Opdateret fil på gh-pages"
          git push
